### PR TITLE
Issue/#105

### PR DESCRIPTION
**Pull request by MostafaVT**

### CODE REVIEW

**Comment by Ahmed-cmd-web** [comment]
Cannot insert the value NULL into column 'semester_code', table 'Advising_Team_119.dbo.Student_Instructor_Course_Take'; column does not allow nulls. INSERT fails.

**Comment by MostafaVT** [comment]
> Cannot insert the value NULL into column 'semester_code', table 'Advising_Team_119.dbo.Student_Instructor_Course_Take'; column does not allow nulls. INSERT fails.

We can able semester_code to accept NULL values easily just by deleting NOT NULL

**Comment by Ahmed-cmd-web** [comment]
ok go aheaad

**Comment by MostafaVT** [comment]
> > Cannot insert the value NULL into column 'semester_code', table 'Advising_Team_119.dbo.Student_Instructor_Course_Take'; column does not allow nulls. INSERT fails.
> 
> We can able semester_code to accept NULL values easily just by deleting NOT NULL

### disclaimer
 it was not that **_easy_**

**Review by Ahmed-cmd-web — APPROVED** [review]

**Pull request merged**
